import type { Metadata } from "next";
import SiteHeader from "../../SiteHeader";

export const metadata: Metadata = {
  title: "Not Everything Needs to Be a Table | Michael Ngo",
  description: "A practical lesson on choosing tables or graphics in proposal writing and design.",
};

const locations = [["Ridgeview Library","2.3 miles"],["Northgate Senior Center","3.7 miles"],["Cedar Park Offices","5.5 miles"],["Lakeside Public Works","6.6 miles"]];

export default function TableLesson(){
  return <main className="bid-desk-article" id="top"><SiteHeader /><article>
    <header className="article-hero"><div><p className="eyebrow">Lessons From the Bid Desk · Entry 01</p><h1>Not Everything Needs to Be a Table</h1><p className="article-deck">A proposal-design lesson I learned after using one of my favorite organizational tools for almost everything.</p><div className="article-meta"><span>By Michael Ngo</span><span>Proposal design</span><span>6 minute read</span></div></div><div className="hero-table" aria-hidden="true"><span>I love tables.</span><div>{Array.from({length:12},(_,i)=><i key={i}/>)}</div><b>Probably too much.</b></div></header>
    <section className="article-copy article-opening"><p>I love tables.</p><p>Probably too much.</p><p>Give me a messy collection of requirements, responsibilities, dates, locations, or prices, and my first instinct is usually:</p><p className="article-punchline">Put it in a table.</p></section>
    <section className="wrestling-break"><div className="gif-frame"><iframe src="https://tenor.com/embed/1549388650773727459" title="Big Show with a table" allowFullScreen loading="lazy"/></div><div><p>At some point, I realized I was approaching proposal design like Big Show entering a Tables Match:</p><blockquote>I saw a problem.<br/>I reached for a table.</blockquote><p>To be fair, tables are incredibly useful. But not everything that <em>can</em> be a table <em>should</em> be a table.</p></div></section>
    <section className="article-copy"><p>Tables organize information, make comparisons easier, and help evaluators retrieve details without digging through several paragraphs. The problem begins when the reader is not really being asked to retrieve information. Sometimes they need to understand an idea.</p></section>
    <section className="comparison-section"><div className="comparison-heading"><div><p className="eyebrow">The same facts, twice</p><h2>The table gives distance.<br/>The map gives context.</h2></div><p>This fictional example uses the same four locations and the same four distances. Only the information architecture changes.</p></div><div className="main-comparison"><div className="example-panel table-panel"><span>The table</span><h3>Existing service locations</h3><table><thead><tr><th>Service location</th><th>Distance</th></tr></thead><tbody>{locations.map(([n,d])=><tr key={n}><td>{n}</td><td>{d}</td></tr>)}</tbody></table><p className="panel-question">How far away are our locations?</p></div><div className="example-panel map-panel"><span>The graphic</span><h3>Operational proximity</h3><div className="proximity-map"><div className="map-road road-one"/><div className="map-road road-two"/><div className="map-pin opportunity">★<small>Opportunity</small></div><div className="map-pin pin-a">A<small>2.3 mi</small></div><div className="map-pin pin-b">B<small>3.7 mi</small></div><div className="map-pin pin-c">C<small>5.5 mi</small></div><div className="map-pin pin-d">D<small>6.6 mi</small></div><strong>All locations are within approximately 2–7 miles</strong></div><p className="panel-question">Why does this opportunity make operational sense?</p></div></div><div className="meaning-line"><span>Table</span><strong>Information</strong><i>→</i><span>Graphic</span><strong>Meaning</strong></div></section>
    <section className="article-copy"><p>The facts have not changed, but the argument has. The map allows the evaluator to see an existing operating footprint around the opportunity. That can suggest nearby supervision, familiar routes, personnel support, and a more practical response structure.</p><p>Information architecture is not decoration applied after the writing is finished. It affects which facts stand out—and whether the selling point is visible at all.</p></section>
    <section className="format-gallery"><div className="comparison-heading"><div><p className="eyebrow">Same facts. Different jobs.</p><h2>Four more reasons to leave the table.</h2></div><p>A table may still be useful as supporting detail. These formats simply do a better job of making the central idea visible.</p></div><div className="format-grid"><MiniFormat number="01" title="Readiness process" table="Training topics and owners" graphic="How a new employee becomes site-ready" type="process"/><MiniFormat number="02" title="Quality cycle" table="Inspection activities" graphic="How an issue becomes an improvement" type="cycle"/><MiniFormat number="03" title="Escalation hierarchy" table="Roles and responsibilities" graphic="Where an issue goes and who owns it" type="hierarchy"/><MiniFormat number="04" title="Transition timeline" table="Tasks and target dates" graphic="How the team moves from award to launch" type="timeline"/></div></section>
    <section className="decision-rule"><p className="eyebrow">The practical rule</p><h2>Am I asking the reader to compare information, or understand an idea?</h2><div><article><span>Compare</span><h3>Use the table.</h3><p>Pricing, requirements, schedules, features, responsibilities.</p></article><article><span>Understand</span><h3>Consider a graphic.</h3><p>Geography, sequence, hierarchy, process, coverage, strategic advantage.</p></article></div></section>
    <section className="article-copy article-ending"><p>I still use tables constantly. Probably more than I should.</p><p>But now I occasionally let a map be a map, a process be a process, and a timeline be a timeline.</p><p>And despite everything Big Show taught me, sometimes the table stays under the ring.</p></section>
    <section className="shape-download"><div><p className="eyebrow">A genuinely useful free thing</p><h2>Steal my shapes.</h2><p>Download five editable PowerPoint examples: a proximity map, readiness process, quality cycle, communication hierarchy, and transition timeline. Recolor them, rewrite them, move them around, or quietly pretend you made them yourself.</p><a className="pill white" href="/downloads/Michael-Ngo-Proposal-Graphic-Starter-Kit.pptx" download>Download the PowerPoint starter kit ↓</a></div><div className="shape-stack" aria-hidden="true"><i/><i/><i/><i/><i/></div></section>
    <nav className="article-footer-nav"><a href="/lessons">← All Bid Desk lessons</a><span>Next: Bid Management Is a Team Sport</span></nav>
  </article><footer><span>© 2026 Michael Ngo</span><span>Lessons From the Bid Desk</span><a href="#top">Back to top ↑</a></footer></main>
}

function MiniFormat({number,title,table,graphic,type}:{number:string,title:string,table:string,graphic:string,type:string}){return <article className="mini-format"><div className={`mini-visual ${type}`}><span>{number}</span><i/><i/><i/><i/><i/></div><small>{title}</small><h3>{table}</h3><b>↓</b><p>{graphic}</p></article>}
