import type { Metadata } from "next";
import SiteHeader from "../../SiteHeader";
import ComparisonCarousel from "./ComparisonCarousel";

export const metadata: Metadata = {
  title: "Not Everything Needs to Be a Table | Michael Ngo",
  description: "A practical lesson on choosing tables or graphics in proposal writing and design.",
};

export default function TableLesson(){
  return <main className="bid-desk-article" id="top"><SiteHeader /><article>
    <header className="article-hero"><div><p className="eyebrow">Lessons From the Bid Desk · Entry 01</p><h1>Not Everything Needs to Be a Table</h1><p className="article-deck">A proposal-design lesson I learned after using one of my favorite organizational tools for almost everything.</p><div className="article-meta"><span>By Michael Ngo</span><span>Proposal design</span><span>6 minute read</span></div></div><div className="hero-table" aria-hidden="true"><span>I love tables.</span><div>{Array.from({length:12},(_,i)=><i key={i}/>)}</div><b>Probably too much.</b></div></header>
    <section className="article-copy article-opening"><p>I love tables.</p><p>Probably too much.</p><p>Give me a messy collection of requirements, responsibilities, dates, locations, or prices, and my first instinct is usually:</p><p className="article-punchline">Put it in a table.</p></section>
    <section className="wrestling-break"><div className="gif-frame"><iframe src="https://tenor.com/embed/1549388650773727459" title="Big Show with a table" allowFullScreen loading="lazy"/></div><div><p>At some point, I realized I was approaching proposal design like Big Show entering a Tables Match:</p><blockquote>I saw a problem.<br/>I reached for a table.</blockquote><p>To be fair, tables are incredibly useful. But not everything that <em>can</em> be a table <em>should</em> be a table.</p></div></section>
    <section className="article-copy"><p>Tables organize information, make comparisons easier, and help evaluators retrieve details without digging through several paragraphs. The problem begins when the reader is not really being asked to retrieve information. Sometimes they need to understand an idea.</p></section>
    <section className="comparison-section"><div className="comparison-heading"><div><p className="eyebrow">The same facts, different jobs</p><h2>Cycle through five table-versus-graphic examples.</h2></div><p>Each pair uses the same underlying information. What changes is the idea the reader can understand at a glance.</p></div><ComparisonCarousel/><div className="meaning-line"><span>Table</span><strong>Information</strong><i>→</i><span>Graphic</span><strong>Meaning</strong></div></section>
    <section className="article-copy"><p>The facts have not changed, but the argument has. The map allows the evaluator to see an existing operating footprint around the opportunity. That can suggest nearby supervision, familiar routes, personnel support, and a more practical response structure.</p><p>Information architecture is not decoration applied after the writing is finished. It affects which facts stand out—and whether the selling point is visible at all.</p></section>
    <section className="decision-rule"><p className="eyebrow">The practical rule</p><h2>Am I asking the reader to compare information, or understand an idea?</h2><div><article><span>Compare</span><h3>Use the table.</h3><p>Pricing, requirements, schedules, features, responsibilities.</p></article><article><span>Understand</span><h3>Consider a graphic.</h3><p>Geography, sequence, hierarchy, process, coverage, strategic advantage.</p></article></div></section>
    <section className="article-copy article-ending"><p>I still use tables constantly. Probably more than I should.</p><p>But now I occasionally let a map be a map, a process be a process, and a timeline be a timeline.</p><p>And despite everything Big Show taught me, sometimes the table stays under the ring.</p></section>
    <section className="shape-download"><div><p className="eyebrow">A genuinely useful free thing</p><h2>Steal my shapes.</h2><p>Download five editable PowerPoint examples: a proximity map, readiness process, quality cycle, communication hierarchy, and transition timeline. Recolor them, rewrite them, move them around, or quietly pretend you made them yourself.</p><a className="pill white" href="/downloads/Michael-Ngo-Proposal-Graphic-Starter-Kit.pptx" download>Download the PowerPoint starter kit ↓</a></div><div className="shape-stack" aria-hidden="true"><i/><i/><i/><i/><i/></div></section>
    <nav className="article-footer-nav"><a href="/lessons">← All Bid Desk lessons</a><span>Next: Bid Management Is a Team Sport</span></nav>
  </article><footer><span>© 2026 Michael Ngo</span><span>Lessons From the Bid Desk</span><a href="#top">Back to top ↑</a></footer></main>
}
