import type { Metadata } from "next";
import SiteHeader from "../SiteHeader";

export const metadata: Metadata = {
  title: "Resume & Career Experience | Michael Ngo",
  description: "Michael Ngo's career across bid management, proposal strategy, public-sector procurement, business intelligence, and process improvement.",
};

const roles = [
  {period:"Mar 2026 – Present",company:"Quality Facility Solutions",title:"Bid Manager",setting:"Commercial facility services",summary:"Leading the full pursuit lifecycle from opportunity sourcing and triage through executive review, pricing coordination, proposal development, and submission.",points:["Evaluate 80–100+ RFPs and RFQs weekly and translate complex requirements into executive-ready bid/no-bid analyses.","Coordinate scope, risk, labor, supplies, staffing assumptions, and pricing inputs with leadership and operations.","Build complete response packages and standardized evaluation frameworks that improve speed, consistency, and clarity."],evidence:[{label:"Interactive Bid Intelligence",href:"/projects/bid-intelligence"},{label:"Excel work sample",href:"/downloads/Michael-Ngo-Bid-Intelligence-Portfolio.xlsx",download:true}]},
  {period:"Oct 2024 – Sept 2025",company:"New York City Housing Authority",title:"Scope Writer",setting:"Public-sector procurement · Remote",summary:"Supporting enterprise procurements from the buyer side, including RFI and RFP documentation, evaluation design, governance materials, and cross-functional modernization initiatives.",points:["Drafted procurement documentation for major initiatives, including NYCHA’s Customer Contact Center modernization.","Developed evaluation frameworks and coordinated vendor Q&A across Legal, IT, Operations, and executive stakeholders.","Produced requirements clarification and decision-support materials to strengthen standardization and stakeholder alignment."],evidence:[{label:"Procurement case study",href:"/projects/qta-case-study"}]},
  {period:"July 2022 – Dec 2023",company:"Once Upon an RFP",title:"Proposal Consultant",setting:"Multi-industry consulting · Remote",summary:"Managing end-to-end proposal assignments across industries while adapting each response to the client’s capabilities, brand, and agency priorities.",points:["Led intake, compliance, drafting, review, and submission activities.","Developed tailored responses rather than relying on generic boilerplate.","Built reusable templates and content libraries to improve clarity and efficiency."],evidence:[]},
  {period:"May 2020 – Oct 2020",company:"Charter Spectrum",title:"Senior Proposal Writer",setting:"Federal telecommunications · Remote contract",summary:"Supporting federal proposals under the Enterprise Infrastructure Solutions program for United States military installations.",points:["Coordinated Legal, Pricing, and Technical inputs for FAR-compliant submissions.","Managed schedule and compliance requirements in a complex federal environment.","Maintained reusable content and supported final reviews and submission."],evidence:[]},
  {period:"May 2017 – Oct 2019",company:"Stellar Services, Inc.",title:"Proposal Specialist",setting:"Government and commercial proposals · On-site",summary:"Building the operational foundation of my proposal career through high-volume public- and private-sector response support.",points:["Supported more than 200 RFPs while maintaining compliance and deadlines.","Coordinated technical inputs and developed tailored responses under compressed schedules.","Maintained templates, content libraries, and repeatable submission workflows."],evidence:[]},
];

const capabilities = ["End-to-end proposal management","Bid / no-bid strategy","Government procurement","Compliance matrices","Requirements traceability","Executive decision support","Pricing coordination","Vendor Q&A","Proposal review cycles","Workflow improvement","AI-assisted development","Dashboard and KPI design"];

export default function ResumePage(){return <main className="career-page">
  <SiteHeader className="career-nav" />
  <section className="career-hero"><div className="career-portrait"><img src="/images/michael-ngo.jpg" alt="Michael Ngo"/><span>Brooklyn, New York</span></div><div><div className="project-kicker"><span>Resume & career experience</span></div><h1>From proposal execution to <em>pursuit intelligence.</em></h1><p className="career-lede">I am a Bid Manager and proposal professional with 8+ years of experience across government, infrastructure, telecommunications, public-sector procurement, and commercial facility services.</p><div className="career-actions"><a className="pill blue" href="/downloads/Michael-Ngo-Resume-2026.pdf" download>Download résumé ↗</a><a className="text-link" href="mailto:Michaelngo5x@gmail.com">Michaelngo5x@gmail.com</a></div><div className="career-facts"><div><strong>8+</strong><span>Years of experience</span></div><div><strong>200+</strong><span>RFPs supported early career</span></div><div><strong>Both</strong><span>Buyer and bidder perspectives</span></div></div></div></section>
  <section className="career-thesis"><p className="eyebrow">Professional progression</p><div><h2>The scope kept expanding.</h2><p>I began by learning the mechanics of compliant proposal delivery. Over time, my work expanded into federal coordination, consulting, buyer-side procurement, pursuit strategy, executive reporting, and process design. The consistent thread is turning complex requirements into organized action.</p></div></section>
  <section className="career-timeline"><div className="career-timeline-heading"><p className="eyebrow">Experience</p><h2>Built across the full lifecycle.</h2><p>Each role added a different perspective on how opportunities are evaluated, organized, communicated, and delivered.</p></div><div className="career-roles">{roles.map((role,index)=><article className="career-role" key={role.company}><div className="role-marker"><span>{String(index+1).padStart(2,"0")}</span><i/></div><div className="role-date"><time>{role.period}</time><small>{role.setting}</small></div><div className="role-content"><p className="role-company">{role.company}</p><h3>{role.title}</h3><p className="role-summary">{role.summary}</p><ul>{role.points.map(point=><li key={point}>{point}</li>)}</ul>{role.evidence.length>0&&<div className="role-evidence"><strong>Related evidence</strong>{role.evidence.map(item=><a key={item.label} href={item.href} {...(item.download?{download:true}:{})}>{item.label} ↗</a>)}</div>}</div></article>)}</div></section>
  <section className="career-capabilities"><div><p className="eyebrow">Core capabilities</p><h2>What I bring to a team.</h2></div><div className="career-skill-grid">{capabilities.map((item,index)=><span key={item}><b>{String(index+1).padStart(2,"0")}</b>{item}</span>)}</div></section>
  <section className="career-perspective"><div><p className="eyebrow">A differentiated perspective</p><h2>I have worked on both sides of the solicitation.</h2></div><div className="perspective-grid"><article><span>Bidder side</span><h3>Build a response that can win.</h3><p>Interpret requirements, coordinate subject-matter experts, align pricing and operations, maintain compliance, and deliver a clear submission on time.</p></article><article><span>Buyer side</span><h3>Create a process that can decide.</h3><p>Structure requirements, evaluation criteria, vendor Q&A, governance materials, and cross-functional input so procurement decisions are consistent and supportable.</p></article><article><span>Systems view</span><h3>Learn from the entire lifecycle.</h3><p>Track decisions, stages, delays, outcomes, and competitive results so each pursuit improves the process that follows it.</p></article></div></section>
  <section className="career-education"><div><p className="eyebrow">Education</p><h2>CUNY Brooklyn College</h2><p>Murray Koppelman School of Business · January 2017</p></div><div className="education-grid"><article><strong>BBA</strong><span>Marketing</span><small>GPA: 3.7</small></article><article><strong>BA</strong><span>Philosophy</span><small>GPA: 3.6</small></article><article className="double-minor"><strong>Double minor</strong><div className="minor-pair"><div><small>Minor 01</small><span>Human Resources Management & Development</span></div><div><small>Minor 02</small><span>Psychology</span></div></div></article></div></section>
  <section className="career-close"><p className="eyebrow">Continue exploring</p><h2>See the work behind the résumé.</h2><p>The portfolio connects this career history to interactive reporting, procurement analysis, proposal development, and verified professional development.</p><div className="actions center"><a className="pill white" href="/projects/bid-intelligence">Bid Intelligence ↗</a><a className="pill outline" href="/projects/qta-case-study">Procurement case study ↗</a><a className="text-link" href="/credentials">Credentials ↗</a></div></section>
  <footer className="project-footer"><span>© 2026 Michael Ngo</span><a href="/">Return to portfolio ↑</a></footer>
  </main>}
