import type { Metadata } from "next";
import SiteHeader from "../SiteHeader";

export const metadata: Metadata = {
  title: "Credentials & Professional Development | Michael Ngo",
  description: "Michael Ngo's verified professional development across project management, procurement, data analytics, AI, governance, and infrastructure.",
};

const credentials = [
  {title:"Google Project Management Professional",issuer:"Google · Coursera",date:"September 2025",category:"Project delivery",image:"/images/certifications/cert-05.jpg",verify:"https://www.coursera.org/account/accomplishments/specialization/KJ7T4MYTJHC5",summary:"Practical grounding in Agile, Scrum, Waterfall, stakeholder engagement, risk management, scheduling, and end-to-end project delivery.",application:"Supports the way I structure pursuit schedules, coordinate contributors, manage dependencies, and keep complex responses moving toward submission."},
  {title:"Global Procurement & Sourcing Specialization",issuer:"Rutgers University · Coursera",date:"October 2025",category:"Procurement",image:"/images/certifications/cert-06.jpg",verify:"https://www.coursera.org/account/accomplishments/specialization/B9X6XYCKCDX4",summary:"Strategic sourcing, supplier evaluation, contract management, negotiation, cost optimization, and sustainable procurement practices.",application:"Strengthens my ability to assess solicitations from both the buyer and bidder perspectives and connect bid decisions to broader sourcing strategy."},
  {title:"AI Engineer for Data Scientists Associate",issuer:"DataCamp",date:"May 2025",category:"Data & AI",image:"/images/certifications/cert-07.jpg",verify:"https://www.datacamp.com/certificate/AEDS0019623140274",summary:"Designing, evaluating, and deploying AI and machine-learning models, including feature engineering, data pipelines, and performance evaluation.",application:"Helps me evaluate where AI can improve analysis and documentation workflows while keeping outputs structured, testable, and decision-focused."},
  {title:"AI Fundamentals",issuer:"DataCamp",date:"March 2025",category:"Data & AI",image:"/images/certifications/cert-08.jpg",verify:"https://www.datacamp.com/skill-verification/AIF0023145532407",summary:"Machine-learning concepts, responsible AI, data ethics, algorithmic bias, interpretability, and operational integration.",application:"Provides a responsible foundation for applying AI to proposal development, compliance review, research, and business processes."},
  {title:"Data Literacy",issuer:"DataCamp",date:"April 2025",category:"Data & AI",image:"/images/certifications/cert-09.jpg",verify:"https://www.datacamp.com/skill-verification/DL0039368256790",summary:"Data interpretation, visualization, analytical reasoning, and communication of complex information to nontechnical audiences.",application:"Directly informs my dashboard design, KPI definitions, executive reporting, and ability to turn bid activity into a useful management narrative."},
  {title:"AI-Powered Proposal Engineer",issuer:"Proposal Industry Experts",date:"February 2024",category:"Proposal strategy",image:"/images/certifications/cert-10.jpg",verify:"https://verified.sertifier.com/en/verify/63075765623501/?ref=email",summary:"AI-assisted proposal workflows, compliance review, response structure, evaluation criteria, clarity, persuasion, and process efficiency.",application:"Connects emerging tools to my core proposal practice without replacing the judgment required to interpret requirements and develop a responsive strategy."},
  {title:"Google Data Analytics Professional",issuer:"Google · Coursera",date:"January 2026",category:"Data & AI",image:"/images/certifications/cert-11.jpg",verify:"https://coursera.org/share/ff328443461139efabf9531b88972b46",summary:"Data cleaning, analysis, visualization, and storytelling using SQL, Excel, Tableau, and a structured analytics process.",application:"Supports the architecture and analysis behind my Bid Intelligence Portfolio, including data quality, calculated metrics, trend analysis, and reporting."},
  {title:"Cyber Security: Governance, Risk & Compliance",issuer:"Macquarie University · Coursera",date:"January 2026",category:"Governance",image:"/images/certifications/cert-12.jpg",verify:"https://coursera.org/share/14b21554503c65264999c8ad4bdca6e4",summary:"Cybersecurity governance, risk assessment, compliance frameworks, security controls, organizational policy, and audit preparation.",application:"Improves how I recognize security, privacy, compliance, and governance requirements within solicitations and cross-functional projects."},
  {title:"Energy Production, Distribution & Safety",issuer:"University at Buffalo · Coursera",date:"February 2026",category:"Infrastructure",image:"/images/certifications/cert-13.jpg",verify:"https://coursera.org/share/5152eb9a0c8013000f110c94bb6250b5",summary:"Energy systems, power distribution, operational risk, regulatory oversight, and safety considerations within infrastructure environments.",application:"Adds domain awareness for public-sector, facilities, utility, and infrastructure-related procurement and project coordination."},
];

export default function CredentialsPage(){return <main className="credentials-page">
  <SiteHeader className="credentials-nav" />
  <section className="credentials-hero"><div><div className="project-kicker"><span>Credentials & professional development</span></div><h1>Learning that strengthens <em>how I work.</em></h1><p>My professional development is deliberately interdisciplinary. It connects the commercial judgment of procurement, the structure of project management, the clarity of data analysis, and the responsibility required to use new technology well.</p><div className="credential-stats"><div><strong>9</strong><span>Verified credentials</span></div><div><strong>6</strong><span>Issuing organizations</span></div><div><strong>2024–26</strong><span>Recent development</span></div></div></div><aside><span>Professional thesis</span><p>The most useful bid and proposal professionals do more than write. They understand the decision, the process, the data, the operating environment, and the people required to deliver.</p><a className="pill blue" href="/downloads/Michael-Ngo-Certification-Portfolio-2026.pdf" download>Download complete portfolio ↗</a></aside></section>
  <section className="credential-framework"><div><p className="eyebrow">How the pieces connect</p><h2>Four lenses on the same work.</h2></div><div className="framework-grid"><article><b>01</b><h3>Structure the work</h3><p>Project management turns deadlines, contributors, risks, and dependencies into a coordinated delivery plan.</p></article><article><b>02</b><h3>Understand the decision</h3><p>Procurement knowledge clarifies what buyers value, how suppliers are assessed, and where commercial risk lives.</p></article><article><b>03</b><h3>Read the evidence</h3><p>Data and AI capabilities make trends visible, improve repeatability, and support decisions without obscuring judgment.</p></article><article><b>04</b><h3>Respect the environment</h3><p>Governance and infrastructure awareness provide context for compliance, safety, security, and operational reality.</p></article></div></section>
  <section className="credential-gallery"><div className="gallery-heading"><div><p className="eyebrow">Verified portfolio</p><h2>Credentials, with practical application.</h2></div><p>Each credential is paired with the way it contributes to my work. Select any certificate image or verification link to review the issuing record.</p></div><div className="credential-list">{credentials.map((item,index)=><article className="credential-entry" key={item.title}><div className="credential-copy"><div className="credential-meta"><span>{String(index+1).padStart(2,"0")}</span><i>{item.category}</i></div><h3>{item.title}</h3><p className="credential-issuer">{item.issuer} · {item.date}</p><p>{item.summary}</p><div className="applied"><strong>How I apply it</strong><p>{item.application}</p></div><a href={item.verify} target="_blank" rel="noreferrer">Verify credential ↗</a></div><a className="certificate-frame" href={item.verify} target="_blank" rel="noreferrer" aria-label={`Verify ${item.title}`}><img src={item.image} alt={`${item.title} certificate awarded to Michael Ngo`}/><span>View verification ↗</span></a></article>)}</div></section>
  <section className="credential-close"><p className="eyebrow">The result</p><h2>A broader toolkit for complex pursuits.</h2><p>These credentials reinforce a working style built around structured analysis, clear communication, practical systems, and continuous improvement.</p><div className="actions center"><a className="pill white" href="/projects/bid-intelligence">Explore Bid Intelligence ↗</a><a className="text-link" href="/projects/qta-case-study">View procurement case study ↗</a></div></section>
  <footer className="project-footer"><span>© 2026 Michael Ngo</span><a href="/">Return to portfolio ↑</a></footer>
  </main>}
